# Generated by Django 5.0 on 2024-03-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={'ordering': ['first_name'], 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterField(
            model_name='teachers',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='phone',
            field=models.SmallIntegerField(max_length=10, unique=True),
        ),
    ]
